lob/lob-java

- src/test/java/com/lob/AreaTest.java
It will check that price is greater than 0.
> Fix AreaTest price check.

- README.md
> Fix artifactId and version in documentation.

- .travis.yml
- README.md
- lob-java-examples/pom.xml
> Add Travis Badge.

- .travis.yml
- README.md
> Add Coveralls Badge.

- README.md
> Removed extra createLetter request

- README.md
> update readme to link to lob docs

- README.md
New version will be released to maven central repository.
We have a new release! :+1:
> Update version 2.0.0 -> 2.0.1

- README.md
> Add icon for maven central repository.

- src/main/java/com/lob/protocol/response/AbstractLobResponse.java
- src/main/java/com/lob/protocol/response/AddressResponse.java
- src/main/java/com/lob/protocol/response/AreaMailResponse.java
- src/main/java/com/lob/protocol/response/BankAccountResponse.java
- src/main/java/com/lob/protocol/response/CheckResponse.java
- src/main/java/com/lob/protocol/response/JobResponse.java
- src/main/java/com/lob/protocol/response/LetterResponse.java
- src/main/java/com/lob/protocol/response/LobObjectResponse.java
- src/main/java/com/lob/protocol/response/PostcardResponse.java
- src/test/java/com/lob/client/test/AddressTest.java
- src/test/java/com/lob/client/test/AreaMailTest.java
- src/test/java/com/lob/client/test/BankAccountTest.java
- src/test/java/com/lob/client/test/CheckTest.java
- src/test/java/com/lob/client/test/JobTest.java
- src/test/java/com/lob/client/test/PostcardTest.java
What: Adds description to lob responses
> feat(response): add description to lob object responses

- src/main/java/com/lob/protocol/response/VerifyAddressResponse.java
- src/test/java/com/lob/client/test/AddressTest.java
What: Adds `message` and it's getters to VerifyAddressResponse
> feat(addresses): add messages to verify addresses

- pom.xml
> Update version 2.0.1 -> 2.0.2

- lob-java-examples/pom.xml
- lob-java-examples/src/main/java/com/lob/examples/AsyncJobExample.java
- lob-java-examples/src/main/java/com/lob/examples/CheckExample.java
- lob-java-examples/src/main/java/com/lob/examples/JobExample.java
- lob-java-examples/src/main/java/com/lob/examples/ObjectFromFileExample.java
- lob-java-examples/src/main/java/com/lob/examples/ObjectFromHtmlExample.java
- lob-java-examples/src/main/java/com/lob/examples/PostcardExample.java
What: Updates examples to be up to date with the latest API changes.
> fix(examples): updated examples to be compliant with latest API version

- README.md
- lob-java-examples/pom.xml
- pom.xml
What: Release wrapper under version 2.1.0
@mgartner @brianseitel @robinjoseph08 @neelk07
> feat(version): upgrade wrapper to version 2.1.0

- lob-java-examples/src/main/java/com/lob/examples/CheckExample.java
- src/main/java/com/lob/protocol/request/BankAccountRequest.java
- src/main/java/com/lob/protocol/request/CheckRequest.java
- src/main/java/com/lob/protocol/response/BankAccountResponse.java
- src/main/java/com/lob/protocol/response/CheckResponse.java
- src/test/java/com/lob/client/test/BankAccountTest.java
- src/test/java/com/lob/client/test/CheckTest.java
Update to accommodate the 2015-11-06 version.
> feat(version): update to accommodate 2015-11-06

- src/main/java/com/lob/protocol/request/PostcardRequest.java
- src/test/java/com/lob/client/test/PostcardTest.java
Make `from` not required for postcards
It isn't required so I'm not sure why it is to begin with...
@mgartner
> fix(postcards): don't require from

- .travis.yml
- README.md
- lob-java-examples/src/main/java/com/lob/examples/AsyncJobExample.java
- lob-java-examples/src/main/java/com/lob/examples/BaseExample.java
- lob-java-examples/src/main/java/com/lob/examples/CheckExample.java
- lob-java-examples/src/main/java/com/lob/examples/CsvVerificationExample.java
- lob-java-examples/src/main/java/com/lob/examples/JobExample.java
- lob-java-examples/src/main/java/com/lob/examples/ObjectFromFileExample.java
- lob-java-examples/src/main/java/com/lob/examples/ObjectFromHtmlExample.java
- lob-java-examples/src/main/java/com/lob/examples/PostcardExample.java
- pom.xml
- src/test/java/com/lob/client/test/BaseTest.java
* Replace API key with one dedicated for Java 
* Update `.travis.yml` to fix issue with `/etc/hosts` relating to Travis https://github.com/travis-ci/travis-ci/issues/5227
* Swap the coveralls info to Lob's account
* Use the SVG badges
> fix(tests): update travis.yml and update to dedicated API key

- src/main/java/com/lob/protocol/request/PostcardRequest.java
- src/main/java/com/lob/protocol/response/PostcardResponse.java
- src/test/java/com/lob/client/test/PostcardTest.java
> adds support for postcard size

- src/main/java/com/lob/client/AsyncLobClient.java
- src/main/java/com/lob/protocol/request/Filter.java
- src/main/java/com/lob/protocol/request/Filters.java
- src/main/java/com/lob/protocol/response/AbstractPagedResponseList.java
- src/main/java/com/lob/protocol/response/AddressResponseList.java
- src/main/java/com/lob/protocol/response/AreaMailResponseList.java
- src/main/java/com/lob/protocol/response/BankAccountResponseList.java
- src/main/java/com/lob/protocol/response/CheckResponseList.java
- src/main/java/com/lob/protocol/response/JobResponseList.java
- src/main/java/com/lob/protocol/response/LetterResponseList.java
- src/main/java/com/lob/protocol/response/LobObjectResponseList.java
- src/main/java/com/lob/protocol/response/PostcardResponseList.java
- src/test/java/com/lob/client/test/AddressTest.java
Make the wrapper compatible with version 2016-01-19
@elnaz
> replace count with limit

- src/main/java/com/lob/protocol/request/CheckRequest.java
- src/test/java/com/lob/client/test/CheckTest.java
Expose the ability to add attachments to the Java wrapper.
Now that it's public, it should be available in all our wrappers.
@mgartner
> feat(checks): add attachment functions

- src/main/java/com/lob/protocol/request/LetterRequest.java
- src/main/java/com/lob/protocol/response/LetterResponse.java
- src/test/java/com/lob/client/test/LetterTest.java
Add support for Lob Version 2016-05-02
@mgartner
> feat(letters): support version 2016-05-02

- src/main/java/com/lob/MoneyDeserializer.java
- src/main/java/com/lob/client/AsyncLobClient.java
- src/main/java/com/lob/client/LobClient.java
- src/main/java/com/lob/protocol/request/AddressRequest.java
- src/main/java/com/lob/protocol/request/AreaMailRequest.java
- src/main/java/com/lob/protocol/request/HasLobParams.java
- src/main/java/com/lob/protocol/request/LobObjectRequest.java
- src/main/java/com/lob/protocol/request/PostcardRequest.java
- src/main/java/com/lob/protocol/request/TargetType.java
- src/main/java/com/lob/protocol/response/AbstractDeleteResponse.java
- src/main/java/com/lob/protocol/response/BankAccountDeleteResponse.java
- src/main/java/com/lob/protocol/response/CheckDeleteResponse.java
- src/main/java/com/lob/protocol/response/ErrorResponse.java
- src/main/java/com/lob/protocol/response/LetterDeleteResponse.java
- src/main/java/com/lob/protocol/response/PostcardDeleteResponse.java
- src/main/java/com/lob/protocol/response/PostcardResponse.java
- src/main/java/com/lob/protocol/response/SettingResponseList.java
- src/main/java/com/lob/protocol/response/StateResponse.java
- src/main/java/com/lob/protocol/response/TrackingEventResponse.java
- src/main/java/com/lob/protocol/response/ZipCodeRouteResponse.java
- src/main/java/com/lob/protocol/response/ZipCodeRouteResponseList.java
- src/test/java/com/lob/client/test/AreaMailTest.java
- src/test/java/com/lob/client/test/BankAccountTest.java
- src/test/java/com/lob/client/test/CheckTest.java
- src/test/java/com/lob/client/test/CountryTest.java
- src/test/java/com/lob/client/test/LetterTest.java
- src/test/java/com/lob/client/test/LobObjectTest.java
- src/test/java/com/lob/client/test/PostcardTest.java
- src/test/java/com/lob/client/test/SettingTest.java
- src/test/java/com/lob/client/test/StateTest.java
What: 
- add delete functionality on postcards, letters and checks
- delete a ton of unused imports
Why: 
- to support delete features
> feat(request): add delete functionality on postcards, letters and checks

- .travis.yml
> fix(travis): use hosts/hostname features

- src/main/java/com/lob/LobApiException.java
- src/main/java/com/lob/client/AsyncLobClient.java
- src/main/java/com/lob/protocol/response/AbstractDeleteResponse.java
- src/main/java/com/lob/protocol/response/AbstractLobResponse.java
- src/main/java/com/lob/protocol/response/AbstractPagedResponseList.java
- src/main/java/com/lob/protocol/response/AbstractResourceResponse.java
- src/main/java/com/lob/protocol/response/AbstractResponse.java
- src/main/java/com/lob/protocol/response/AbstractResponseList.java
- src/main/java/com/lob/protocol/response/BaseAddressResponse.java
- src/main/java/com/lob/protocol/response/SettingResponse.java
- src/main/java/com/lob/protocol/response/SettingResponseList.java
- src/main/java/com/lob/protocol/response/VerifyAddressResponse.java
- src/test/java/com/lob/client/test/AddressTest.java
- src/test/java/com/lob/client/test/AreaMailTest.java
- src/test/java/com/lob/client/test/BankAccountTest.java
- src/test/java/com/lob/client/test/CheckTest.java
- src/test/java/com/lob/client/test/CountryTest.java
- src/test/java/com/lob/client/test/IdTest.java
- src/test/java/com/lob/client/test/JobTest.java
- src/test/java/com/lob/client/test/LetterTest.java
- src/test/java/com/lob/client/test/LobObjectTest.java
- src/test/java/com/lob/client/test/PostcardTest.java
- src/test/java/com/lob/client/test/SettingTest.java
- src/test/java/com/lob/client/test/StateTest.java
- src/test/java/com/lob/client/test/UtilTest.java
- src/test/java/com/lob/client/test/VerifyAddressTest.java
- src/test/java/com/lob/client/test/ZipCodeRouteTest.java
> feat(headers): add headers to response objects

- README.md
- lob-java-examples/pom.xml
- pom.xml
> chore(settings): update version in README and example

- README.md
- pom.xml
- src/main/java/com/lob/client/AsyncLobClient.java
- src/main/resources/project.properties
- This will allow us to have more insight into what version of the wrapper and Java our customers are using.
- VersionEye is having some some HTTPS certificate issues as well as this badge is not tied to a lob.com account
> feat(user-agent) add custom user-agent to wrapper

- README.md
> Add Gradle to the README

- .travis.yml
- pom.xml
- src/main/java/com/lob/LobApiException.java
- src/main/java/com/lob/client/AsyncLobClient.java
- src/test/java/com/lob/client/test/AddressTest.java
- src/test/java/com/lob/client/test/AsyncLobClientTest.java
**What**
- TravisCI has been erring on `opendjk6` since mid December 2016
- This was not possible before since NING `1.9.X` dropped support for Java 6.
> feat(ning): upgrade to latest NING version

- src/main/java/com/lob/protocol/request/AbstractDataFieldRequest.java
- src/main/java/com/lob/protocol/request/AreaMailRequest.java
- src/main/java/com/lob/protocol/request/CheckRequest.java
- src/main/java/com/lob/protocol/request/LetterRequest.java
- src/main/java/com/lob/protocol/request/PostcardRequest.java
- src/test/java/com/lob/client/test/CheckTest.java
- src/test/java/com/lob/client/test/LetterTest.java
What: update wrapper to use merge_variables instead of data
Why: new version with HTML features
> chore(resources): update to use merge_variables

- lob-java-examples/README.md
- lob-java-examples/pom.xml
- lob-java-examples/src/main/java/com/lob/examples/CsvLetterExample.java
- lob-java-examples/src/main/java/com/lob/examples/CsvPostcardExample.java
What: update examples to use mergeVariables instead of data
Why: new HTML feature version
[ENG-3545](https://lobsters.atlassian.net/browse/ENG-3545)
> chore(examples): update to use mergeVariables 

- src/main/java/com/lob/protocol/response/USVerificationResponse.java
**What**
- add address-type and geocoding information to wrapper
> feat(us-verification): add address-type and geocoding to wrapper

- src/main/java/com/lob/model/Postcard.java
- src/main/java/com/lob/net/ResponseGetter.java
- src/test/java/com/lob/model/PostcardTest.java
> chore(postcards): remove deprecated message field

- src/main/java/com/lob/model/USVerification.java
- src/test/java/com/lob/model/AreaTest.java
> chore(us-verification): update US Verification model to support new API Version

- .travis.yml
- pom.xml
- src/main/java/com/lob/exception/APIException.java
- src/main/java/com/lob/exception/AuthenticationException.java
- src/main/java/com/lob/exception/InvalidRequestException.java
- src/main/java/com/lob/exception/LobException.java
- src/main/java/com/lob/exception/RateLimitException.java
- src/main/java/com/lob/model/Address.java
- src/main/java/com/lob/model/BankAccount.java
- src/main/java/com/lob/model/Check.java
- src/main/java/com/lob/model/Letter.java
- src/main/java/com/lob/model/Postcard.java
- src/main/java/com/lob/model/TrackingEvent.java
- src/main/java/com/lob/net/APIResource.java
- src/main/java/com/lob/net/IResponseGetter.java
- src/main/java/com/lob/net/MultipartProcessor.java
- src/main/java/com/lob/net/RequestOptions.java
- src/main/java/com/lob/net/ResponseGetter.java
- src/test/java/com/lob/model/CheckTest.java
- src/test/java/com/lob/model/IntlVerificationTest.java
- src/test/java/com/lob/model/LetterTest.java
- src/test/java/com/lob/model/PostcardTest.java
- src/test/java/com/lob/net/LobResponseTest.java
> update to java 8 and drop joda-time

- src/main/java/com/lob/net/RequestOptions.java
- src/main/java/com/lob/net/ResponseGetter.java
This change is to address my question on Lob support request (25029). I added the proxy capability as per Ami's feedback. So please review the changes and see if we can build a new version to support proxy.
----- FYI
Hey Liqun,
Unfortunately we don't support this out of the box in our java library, since we always default to api.lob.com. You are free to fork our library and add this functionality in yourself.
Best,
Ami
> Support Http Proxy

- pom.xml
**What:** Bump jackson version to 2.9.0.
**Why:** Security fix.
> chore(pom): update jackson version

- pom.xml
Fixing security vulnerability: https://lobsters.atlassian.net/browse/ENG-9635
> chore(pom): update jackson to 2.9.8

- src/test/java/com/lob/model/IntlVerificationTest.java
Updates the International Verifications test to check for the correct response code now that we have added a new International Verifications test mode.
> chore(intl-ver): update intl ver test

- pom.xml
- src/main/java/com/lob/exception/ParsingException.java
- src/main/java/com/lob/model/Check.java
- src/main/java/com/lob/model/Letter.java
- src/main/java/com/lob/model/Postcard.java
- src/test/java/com/lob/model/CheckTest.java
- src/test/java/com/lob/model/LetterTest.java
- src/test/java/com/lob/model/PostcardTest.java
Allows nested merge variables
For advanced templating syntax
> feat(merge-variables): allow nested merge variables

- README.md
- pom.xml
- src/main/java/com/lob/model/Letter.java
- src/main/java/com/lob/model/LetterSize.java
- src/test/java/com/lob/model/LetterTest.java
> chore(letter-size) add letter size option

- src/test/java/com/lob/model/SelfMailerTest.java
Updates two failing tests due to an upstream bug fix in the API
> fix(self-mailers): Fix failing tests due to an upstream API fix

- src/main/java/com/lob/model/Check.java
- src/main/java/com/lob/model/Letter.java
- src/main/java/com/lob/model/Postcard.java
- src/main/java/com/lob/model/SelfMailer.java
Didn't change tests for now - as they require adding a new billing group, which is not supported in the model/logic yet
> add billing group id to model

- src/main/java/com/lob/model/BillingGroup.java
- src/main/java/com/lob/model/BillingGroupCollection.java
- src/main/java/com/lob/model/Check.java
- src/main/java/com/lob/model/Letter.java
- src/main/java/com/lob/model/Postcard.java
- src/main/java/com/lob/model/SelfMailer.java
- src/test/java/com/lob/model/BillingGroupTest.java
* https://lobsters.atlassian.net/browse/BILL-891
* Add billing group support to the java sdk.  (`CREATE`, `UPDATE`, `RETRIEVE`, and `LIST`).
> BILL-891(feat): add Billing_Group support

- src/main/java/com/lob/model/USVerification.java
- src/test/java/com/lob/model/USVerificationTest.java
Added the lob confidence score to the java us verifications class
Also wrote a test verifying, if we receive it, it will be in the object.
> feat: Add confidence score to the us verification

- .github/workflows/run_tests_forked.yml
- pom.xml
Creates a workflow for PRs coming from forked repos
> Add gh action for forked repos

- __tests__/Integration/CardOrderApiSpecTest.java
- __tests__/Integration/CardsApiSpecTest.java
Added integration tests for card orders and cards
> Cards integration test

- __tests__/Api/CardOrdersApiTest.java
- __tests__/Integration/CardOrderApiSpecTest.java
- __tests__/Model/CheckEditableTest.java
- __tests__/Model/LetterEditableTest.java
- __tests__/Model/LetterTest.java
- __tests__/Model/PostcardEditableTest.java
- __tests__/Model/SelfMailerEditableTest.java
- __tests__/Model/SelfMailerTest.java
- src/main/java/com/lob/api/client/CardOrdersApi.java
- src/main/java/org/openapitools/client/model/CheckEditable.java
- src/main/java/org/openapitools/client/model/Letter.java
- src/main/java/org/openapitools/client/model/LetterEditable.java
- src/main/java/org/openapitools/client/model/PostcardEditable.java
- src/main/java/org/openapitools/client/model/SelfMailer.java
- src/main/java/org/openapitools/client/model/SelfMailerEditable.java
Added Aditis fix of letters
Added my fix for oneOf
> fix: fix oneOf and letters in java 

- CODE_SNIPPETS.md
Addded the code snippets that wwere generated from sdks_open_api_gen
> chore: Code snippet tweaks from generator

- README.md
[ticket](https://lobsters.atlassian.net/browse/DXP-1196)
> update readme for new sdk

- __tests__/Api/IntlAutocompletionsApiTest.java
- __tests__/Integration/IntlAutocompletionsApiSpecTest.java
- src/main/java/com/lob/model/IntlSuggestions.java
[ticket](https://lobsters.atlassian.net/browse/DXP-1126)
[SDK generator](https://github.com/lob/sdks_openapi_gen/pull/256)
Regenerated SDK doesn't work out-of-the-box. Problems with Card, Letter, and ReturnEnvelope.
> add intlAutocompletionsApi tests

- README.md
[ticket](https://lobsters.atlassian.net/browse/DXP-1228)
> remove legacy docs link from old SDK

- __tests__/Integration/ZipLookupApiSpecTest.java
- src/main/java/com/lob/api/Configuration.java
[ticket](https://lobsters.atlassian.net/browse/DXP-716)
> ziplookups spec test

- README.md
[ticket](https://lobsters.atlassian.net/browse/DXP-1405)
> docs: add legacy sdk link

- __tests__/Integration/LettersApiSpecTest.java
- __tests__/Integration/PostcardsApiSpecTest.java
- __tests__/Integration/SelfMailerApiSpecTest.java
- src/main/java/com/lob/model/SelfMailer.java
There was a bug found by one of our customrs with self mailers
the issue was the return response was expected to be Self Mailer and we were using Self Mailer Editable
> Fix self mailer model bug

- build.gradle
- build.sbt
- pom.xml
https://lobsters.atlassian.net/browse/SUP-810
- Bring SDK version tags into alignment
- Update `nexus-staging-maven-plugin` version and add `<pluginRepositories>` to try to fix error with `mvn release`
> SUP-810 | Update nexus-staging-maven-plugin version and SDK version
