lob/lob-java

src/main/java/com/lob/protocol/response/AreaMailResponse.java, src/main/java/com/lob/protocol/response/CheckResponse.java, src/main/java/com/lob/protocol/response/JobResponse.java, src/main/java/com/lob/protocol/response/LetterResponse.java, src/main/java/com/lob/protocol/response/PostcardResponse.java, src/test/java/com/lob/client/test/AreaMailTest.java, src/test/java/com/lob/client/test/CheckTest.java, src/test/java/com/lob/client/test/JobTest.java, src/test/java/com/lob/client/test/LetterTest.java, src/test/java/com/lob/client/test/PostcardTest.java
What: remove `status` field from postcards, letters, jobs and area mail response.
Why: it was removed from the latest version of the API
@pon @mgartner @elnaz @robinjoseph08 @neelk07
=> fix(status): remove status fields from wrapper

src/main/java/com/lob/protocol/request/AddressRequest.java, src/main/java/com/lob/protocol/response/AddressResponse.java, src/test/java/com/lob/client/test/AddressTest.java
What: 
- Adds `company` support to AddressRequest and AddressResponse
- Removes checkPresent on name
@pon
=> feat(addresses): add company to addresses and removes checkPresent

pom.xml
It points to the javadev/lob-java, the same as in readme.md.
=> Restore coverals token.

src/main/java/com/lob/protocol/request/CheckRequest.java, src/test/java/com/lob/client/test/CheckTest.java
What: Adds the ability to add a `file` property to the CheckRequest builder through the `.file()` builder function.
Why: It's currently missing from the wrapper.
@mgartner @elnaz @robinjoseph08 @brianseitel @neelk07
=> feat(checks): add file functionality to checks

src/main/java/com/lob/Util.java, src/main/java/com/lob/id/LobId.java, src/test/java/com/lob/client/test/IdTest.java, src/test/java/com/lob/client/test/UtilTest.java
Remove `checkIdentifierFor`.
Because it isn't necessary, and it was causing some tests to fail because they were pulling "new" `bank_address`es that had an id of `adr_bank_address` which isn't "valid".
@elnaz
=> feat(id): remove checkIdentifierFor

src/main/java/com/lob/protocol/request/LetterRequest.java, src/main/java/com/lob/protocol/response/LetterResponse.java, src/test/java/com/lob/client/test/LetterTest.java
Add the capability to create letters with `extra_service`, `return_envelope`, and `perforated_page`.
They were missing from the wrapper despite the fact the API had the functionality.
@elnaz
=> feat(letters): add extra_service, return_envelope, and perforated_page

src/main/java/com/lob/protocol/request/CheckRequest.java, src/main/java/com/lob/protocol/response/LetterResponse.java, src/main/java/com/lob/protocol/response/PostcardResponse.java, src/test/java/com/lob/client/test/CheckTest.java, src/test/java/com/lob/client/test/LetterTest.java, src/test/java/com/lob/client/test/PostcardTest.java
Update to accommodate the new API version
For this update, I decided to go for the "Deprecating" approach instead of the complete removal approach. Now when people update their wrapper, they'll see the functions are deprecated, but they will in fact still work. This was easy to do for these changes because all it was was a param rename.
=> feat(version): update for 2015-11-23

src/main/java/com/lob/protocol/response/AbstractPagedResponseList.java, src/main/java/com/lob/protocol/response/AbstractResponseList.java, src/main/java/com/lob/protocol/response/AddressDeleteResponse.java, src/main/java/com/lob/protocol/response/AddressResponseList.java, src/main/java/com/lob/protocol/response/LetterResponse.java, src/main/java/com/lob/protocol/response/PostcardResponse.java, src/main/java/com/lob/protocol/response/TrackingEventResponse.java, src/main/java/com/lob/protocol/response/TrackingResponse.java, src/test/java/com/lob/client/test/LetterTest.java, src/test/java/com/lob/client/test/PostcardTest.java
Add a more comprehensive list of properties to expose for our products (such as `thumbnails`, `url`, and `tracking`), including adding a `TrackingEventResponse` object.
Because it's being returned from the API, it should be exposed so our customers can utilize them.
* I'm removing a lot of unnecessary imports in a few files as well.
* I'm converting some old references to `Collection` to `List` to provide a sense a ordering (and since a `List` is a subclass of `Collection`, this shouldn't break anything).
If you see I'm missing any properties, let me know. I'll like to get all of them in.
@mgartner
=> feat(response): add tracking_events and other properties

lob-java-examples/src/main/java/com/lob/examples/CheckExample.java, src/main/java/com/lob/protocol/request/BankAccountRequest.java, src/main/java/com/lob/protocol/response/BankAccountResponse.java, src/main/java/com/lob/protocol/response/TrackingResponse.java, src/test/java/com/lob/client/test/BankAccountTest.java, src/test/java/com/lob/client/test/CheckTest.java, src/test/java/com/lob/client/test/PostcardTest.java
- Adds support for accountType to bank accounts
- Updates the check example to provide an account type when creating a bank account
- Removes support for tracking link
- Updates tracking tests to expect a null tracking by default
=> Support API version 2016-03-21

src/main/java/com/lob/protocol/request/CheckRequest.java, src/main/java/com/lob/protocol/request/LetterRequest.java, src/main/java/com/lob/protocol/request/PostcardRequest.java, src/main/java/com/lob/protocol/response/CheckResponse.java, src/main/java/com/lob/protocol/response/LetterResponse.java, src/main/java/com/lob/protocol/response/PostcardResponse.java, src/test/java/com/lob/client/test/CheckTest.java, src/test/java/com/lob/client/test/LetterTest.java
=> feat(mail_type): allow custom mail_type with postcards, letters and checks

src/main/java/com/lob/protocol/response/USVerificationResponse.java, src/test/java/com/lob/client/test/USVerificationTest.java
=> fix(us-verification): make Component and Deliverability public

.travis.yml, pom.xml, src/main/java/com/lob/Lob.java, src/main/java/com/lob/exception/APIException.java, src/main/java/com/lob/exception/AuthenticationException.java, src/main/java/com/lob/exception/LobException.java, src/main/java/com/lob/model/Address.java, src/main/java/com/lob/model/AddressCollection.java, src/main/java/com/lob/model/LobCollection.java, src/main/java/com/lob/net/APIResource.java, src/main/java/com/lob/net/IResponseGetter.java, src/main/java/com/lob/net/LobResponse.java, src/main/java/com/lob/net/RequestOptions.java, src/main/java/com/lob/net/ResponseGetter.java, src/test/java/com/lob/BaseTest.java, src/test/java/com/lob/model/AddressTest.java, src/test/java/com/lob/net/LobResponseTest.java, src/test/java/com/lob/net/RequestOptionsTest.java, src/test/java/com/lob/net/ResponseGetterTest.java
This is the first PR (of many) that includes the new Java wrapper.
**What**
=> chore(httpClient): add HTTP base with Address retrieve/list resources

src/test/java/com/lob/model/AreaTest.java
**What**
**Why**
The monthly delivery statistics update means that these values might change on a monthly basis. While the route will always be valid (in the near long-term) the price and number of addresses is likely to change thus break the previous test.
=> chore(tests): fix area tests to be more resilient

src/main/java/com/lob/model/USVerification.java, src/main/java/com/lob/net/APIResource.java, src/main/java/com/lob/net/IResponseGetter.java, src/main/java/com/lob/net/ResponseGetter.java, src/test/java/com/lob/model/USVerificationTest.java
=> feat(us-verifications): allow passing queries in verification creation

src/main/java/com/lob/model/USVerification.java, src/test/java/com/lob/model/USVerificationTest.java
=> feat(us-verifications): Support single line address verifications

src/main/java/com/lob/model/Address.java, src/test/java/com/lob/model/AddressTest.java
Adds the `recipient_moved` param to the `AddressResponse` class ([docs](https://lob.com/docs#addresses_object))
=> fix(recipient-moved): add recipient_moved param to address

src/main/java/com/lob/model/Check.java, src/main/java/com/lob/model/Letter.java, src/main/java/com/lob/model/Postcard.java, src/test/java/com/lob/model/CheckTest.java, src/test/java/com/lob/model/LetterTest.java, src/test/java/com/lob/model/PostcardTest.java
**What:** Adds merge_variables to `postcards`, `checks`, and `letters` Java wrappers.
**Why:** Business ask from customers to be able to see the merge_variables they set previously.
**Details:**
- Makes it so customers can see the merge_variables that they set in the API response when using the Java Lob wrapper.
- Adds/refactors existing tests.
**Notes:**
- *JIRA:* [ENG-10673](https://lobsters.atlassian.net/browse/ENG-10673)
- *Related PRs:*
- lob/lob-api#5190 (**DO NOT MERGE** until this PR is merged)
- *Affected endpoints:*
- All `postcards` endpoints
- All `checks` endpoints
- All `letters` endpoints
- *Testing instructions:* Use the Java wrapper locally.
=> feat(merge_variables): adds them to API response

.travis.yml
Update the JDK version we test our java library against. Travis has removed OracleJDK8 from their available JDKs so I've updated the list to all available development kits.
=> chore(travis): add openjdk10, openjdk11, oraclejdk11 and remove oraclejdk8 (deprecated)

src/main/java/com/lob/model/Event.java, src/main/java/com/lob/model/EventType.java, src/test/java/com/lob/model/EventTest.java
```java
ObjectMapper mapper = new ObjectMapper().registerModule(new JavaTimeModule());
Event event = mapper.readValue(WEBHOOK_PAYLOAD, Event.class);
```
Closes #133
=> feat(events): add event model to allow webhook deserialization

src/main/java/com/lob/model/USAutocompletion.java, src/test/java/com/lob/model/USAutocompletionTest.java
Adds ability to set the `zip_code` param for autocomplete requests.
=> fix(zip): add ability to set zip code for autocomplete

src/main/java/com/lob/model/Check.java, src/test/java/com/lob/model/CheckTest.java
- If you have a numeric representation of the amount you'd like to create the check for you can use built-in functions to get the string represenation. Make sure you don't lose any precision while converting the number into a string. For example you can use [`BigDecimal.toPlainString()`](https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html#toPlainString()) or [`Double.toString()`](https://docs.oracle.com/javase/7/docs/api/java/lang/Double.html#toString()).
Fixes #158
=> fix(check): use double for check amount and add setAmount(String amount)

pom.xml, src/main/java/com/lob/net/ResponseGetter.java
Fix #157 
Android defaults to version 1.3 of apache.common.codec - even when a newer version is included you dependency.  For lob-java we specify version 1.10. 
Authorization header currently uses the method Base64.encodeBase64String() which is only supported in version 1.4 and higher of apache.common.codec.
To resolve this, I've replace Base64.encodeBase64String() with new String(Base64.encodeBase64()). 
Both achieve the same result, but with this new String() approach it is compatible with version 1.3 and higher of apache.common.codec.
=> Fix base64encodestring

CODE_SNIPPETS.md, api/openapi.yaml, src/main/java/com/lob/api/client/ChecksApi.java, src/main/java/com/lob/api/client/LettersApi.java, src/main/java/com/lob/api/client/PostcardsApi.java, src/main/java/com/lob/api/client/SelfMailersApi.java
=> fix-geocode-snippets

CODE_SNIPPETS.md, MIGRATION.md, README.md, __tests__/Helper/lobster-family.csv, __tests__/Integration/IdentityValidationApiSpecTest.java, api/openapi.yaml, docs/SingleLineAddress.md, docs/UsVerificationsWritable.md, src/main/java/com/lob/model/UsVerificationsWritable.java
[GC-1943](https://lobsters.atlassian.net/browse/GC-1943)
Updates Lob address from "210 King St." to "2261 Market Street STE 5668, 94114"
[Tests fail on main](https://github.com/lob/lob-java/actions/workflows/run_tests.yml). I created [GC-2168](https://lobsters.atlassian.net/browse/GC-2168) to fix these tests.
[GC-1943]: https://lobsters.atlassian.net/browse/GC-1943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GC-2168]: https://lobsters.atlassian.net/browse/GC-2168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GC-1943/update-Lob-address
